### ISSUE TITLE
Can't use script

### ISSUE THREAD

**Issue by ZeroX1ng** [sudo-do/discord-selfbot-owo-bot#15]
I am a rookie and basically don’t understand code, so I may have asked a stupid question, but I still need help, because this script was really great before!
I can't use it after the update, the screenshot is as follows:
![image](https://user-images.githubusercontent.com/34992990/126886966-2f32851a-a122-49b6-ab4c-f4491255f51b.png)

May I ask what went wrong? （PS：Because I am in a special country, I may have a little network problem. I have used proxy software, but I may not be able to correctly set up proxy access for python）

**Comment by sudo-do** [comment]
try delete settings.json

**Comment by sudo-do** [comment]
also yes, that looks like a network problem. requests.get.text variable is NoneType

**Comment by ZeroX1ng** [comment]
> try delete settings.json
This doesn't work, so how to simply set the network access of this script to local socks or http proxy?

**Comment by sudo-do** [comment]
if you use a vpn software instead, it should work.

> simply set the network access of this script to local socks or http proxy?

i need to check the docs

**Comment by sudo-do** [comment]
you need to add *proxy_host="host", proxy_port="port"* to line 67, so, it will look like *client=discum_c844aef.Client(token=bot.token, proxy_host="host", proxy_port="port", log=False)*

and i'll make an update today

**Comment by ZeroX1ng** [comment]
![image](https://user-images.githubusercontent.com/34992990/126937693-fcc156b3-6b89-4385-8337-6c6ffecbfe3a.png)
It still doesn't work, maybe I should just wait for your update, but I'm pretty sure it's the problem caused by the network (proxy).

**Comment by sudo-do** [comment]
this commit should do the job

**Comment by sudo-do** [comment]
please close this issue if the problem is solved, else, tell me what gone wrong. thx

**Comment by ZeroX1ng** [comment]
![image](https://user-images.githubusercontent.com/34992990/127359836-d63c4236-30ab-45ae-b43a-7ebefbfbcf06.png)
sad, maybe this is my own problem. try 2 port , same isssue . But it worked when I use my router for a full proxy.

**Comment by sudo-do** [comment]
also, try with this package too, has the latest discum, and debugging is on, don't forget to send results here lol
[discord-selfbot-owo-bot.zip](https://github.com/sudo-do/discord-selfbot-owo-bot/files/6895083/discord-selfbot-owo-bot.zip)

**Comment by ZeroX1ng** [comment]
![image](https://user-images.githubusercontent.com/34992990/127428394-cd18756a-dfde-4513-b788-6b53972bb8e9.png)
![image](https://user-images.githubusercontent.com/34992990/127428511-5c72a298-a5f2-4250-bef3-a7a9fa15f386.png)
both socks and http proxy has failed

**Comment by sudo-do** [comment]
they said it's fixed with commit https://github.com/Merubokkusu/Discord-S.C.U.M/commit/82c814bef9d026e3b922c56340af7e1b7e677447 , can you please try again with following update?

**Comment by ZeroX1ng** [comment]
Still the same prompt, should I give up？, I even tried to reset my computer’s network settings, maybe my proxy tool "qv2ray" is faulty, although I can access other URLs that need proxy normally, but only This script doesn't work。This only happened on my personal pc. On my other office computer, the script worked very well (may also have some problems: the verification code prompt could not be recognized,If I encounter it again, I should submit\add a new issue)

**Comment by ZeroX1ng** [comment]
![image](https://user-images.githubusercontent.com/34992990/127968579-e3512429-f9ab-4cc6-85f1-6eb5cb392fb2.png)
On another computer that can run script normally, I also encountered this problem today, :(

**Comment by sudo-do** [comment]
this error is because of a short network connection drop, not important tho, just reset the script

**Comment by sudo-do** [comment]
im working on a entire re-write, so i wont fix any issues for now, all of them will be fixed on re-write version

**Comment by ZeroX1ng** [comment]
Looking forward to your new version release

**Comment by lehoailam3005** [comment]
![image](https://user-images.githubusercontent.com/53231154/137667386-3539aaf4-7917-4441-a708-82e680996cbc.png)
I run in a personal machine without having problems but I ran it at VPS this error
